---
sudo: false
language: python
python:
  - "3.6"
cache: pip
install:
  - cd code
  - pip install codecov pytest-django pytest-cov numpy Cython
  - pip install -r requirements.txt
script:
  - pytest --cov=./
after_success:
  - codecov --token=$CODECOV_TOKEN
