# Generated by Django 2.0.4 on 2018-05-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluation', '0003_auto_20180511_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardCurve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('jaccard', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluation.Session')),
            ],
        ),
    ]
