# Generated by Django 2.0.13 on 2019-04-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboardcurve',
            old_name='jaccard',
            new_name='metric',
        ),
    ]
