# Generated by Django 2.0.4 on 2018-05-04 06:12

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_participant_registration_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='country',
            field=django_countries.fields.CountryField(default='CH', max_length=2),
            preserve_default=False,
        ),
    ]
