# Generated by Django 2.0.4 on 2018-05-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('user_id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=254)),
                ('organization', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
